[build-system]
requires = ["setuptools>42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "tardis_pytorch/_version.py"

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
testpaths = [
    "tests",
]