name: conda-publish-env
numpy: 1.23
dependencies:
  - python>=3.10,<3.12
  - pytorch>=1.12.0
  - numpy>=1.21.0
  - pandas>1.3.0
  - tifffile>2021.11.0
  - imagecodecs
  - scikit-learn>1.0.1
  - scikit-image>0.19.2
  - scipy>=1.8.1
  - pillow
  - open3d
  - requests>2.28.0
  - ipython>8.0.0
  - click>8.0.4
  - pyvista
  - plyfile