name: conda-publish-env
python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11
channels:
  - open3d-admin
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pytorch>=1.12.0
  - numpy>=1.21.0
  - pandas>1.3.0
  - tifffile>2021.11.0
  - imagecodecs>2021.11.00
  - scikit-learn>1.0.1
  - scikit-image>0.19.2
  - scipy>=1.8.1
  - pillow>10.0.0
  - open3d>=0.9.0
  - requests>2.28.0
  - ipython>8.0.0
  - click>8.0.4