{% set version = "0.1.2" %}

package:
  name: "tardis-em"
  version: {{ version }}

source:
    git_url: https://github.com/SMLC-NYSBC/TARDIS.git
    git_tag: main

requirements:
    build:
        - python
        - setuptools
    run:
        - python>=3.7
        - pytorch>=1.12.0
        - numpy>=1.21.0
        - pandas>1.3.0
        - tifffile
        - imagecodecs
        - scikit-learn>1.0.1
        - scikit-image>0.19.2
        - scipy>=1.8.1
        - requests
        - ipython
        - click
    optional:
        edt: "Extra post-processing between Semantic and Instance segmentation. Depreciated"
        plyfile: "Enable support for .ply files."
        pyvista: "Enable output for .stl file types"
        nvidia-smi: "Enable additional GPU log options"

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"


about:
    home: https://github.com/SMLC-NYSBC/TARDIS
    license: GPLv3
    license_file: LICENSE