{% set data = load_setup_py_data() %}

package:
  name: "tardis-em"
  version: {{ data.get['version'] }}

source:
    git_url: https://github.com/SMLC-NYSBC/TARDIS.git
    git_tag: main

requirements:
    build:
        - python
        - setuptools
    run:
        - python>=3.8
        - pytorch>=1.12.0
        - numpy>=1.21.0
        - pandas>1.3.0
        - tifffile>2021.11.0
        - imagecodecs>2021.11.00
        - scikit-learn>1.0.1
        - scikit-image>0.19.2
        - scipy>=1.8.1
        - edt>=2.3.0
        - pillow>10.0.0
        - open3d>=0.9.0
        - requests>2.28.0
        - ipython>8.0.0
        - click>8.0.4
    optional:
        plyfile: "Enable support for .ply files."
        pyvista: "Enable output for .stl file types"
        nvidia-smi: "Enable additional GPU log options"

build:
    noarch: python
    number: 0
    script: "python setup.py install --single-version-externally-managed --record=record.txt"

about:
    home: {{ data['url'] }}
    license: {{ data['license'] }}
    summary: {{ data['description'] }}