name: Python PyTest

on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  test_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade coverage
          python -m pip install flake8 pytest
          pip install -r requirements.txt
          pip install -e .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --ignore=E731, W504, E722, F821, F841 --show-source --statistics

      - name: Test with pytest
        run: |
          pytest
