name: Python PyTest

on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/**'

jobs:
  test_build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade coverage
          python -m pip install flake8 pytest

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -e .
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --ignore=E731,W504,E722,E127,E126,E241  --max-line-length=120 --show-source --statistics

      - name: Test with pytest
        run: |
          pytest
